//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoDS_Csharp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wpf_dbEntities : DbContext
    {
        public wpf_dbEntities()
            : base("name=wpf_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ImportaDocumento> ImportaDocumentos { get; set; }
        public virtual DbSet<Perfil> Perfils { get; set; }
        public virtual DbSet<UsuarioSistema> UsuarioSistemas { get; set; }
    }
}
